USE Northwind
GO
--10.1 HACER SELECT
SELECT * FROM CATALOGOS.Categories
GO
--10.2 HACER INSERT
INSERT INTO VENTAS.Products(ProductName,SupplierID,CategoryID,UnitPrice,UnitsInStock) 
VALUES('NUEVO PRODUCTO',1,1,150,10)
SELECT * FROM VENTAS.Products
ORDER BY ProductID DESC
--10.3 HACER UPDATE
UPDATE VENTAS.Products SET
ProductName='PRODUCTO ACTUALIZADO'
WHERE ProductID=78
--10.4 HACER DELETE
DELETE VENTAS.Products
WHERE ProductID=78