-- PRACTICA 3
--UNIDAD 3
--NUÑEZ CARVAJAL JOSE TADEO
--09/03/26
/*
Tenemos una base de datos para el hospital del IMSS no. 1 de Tepic, deseamos que la
reorganices de acuerdo a las siguientes indicaciones.
*/
--1. Conoce la bd observando que tablas la integran y generando el Diagrama de la BD
USE HospitalIMSS
GO
--
SELECT * FROM SYS.objects
WHERE TYPE='U'
SELECT * FROM ConsultasMedicas;--2
SELECT * FROM Consultorios;--2
SELECT * FROM Departamentos--2
SELECT * FROM DetalleFactura--2
SELECT * FROM DetalleReceta--2
SELECT * FROM Enfermeros
SELECT * FROM Especialidades--2
SELECT * FROM Facturas--2
SELECT * FROM Habitaciones--0
SELECT * FROM Internamientos--0
SELECT * FROM Medicamentos--2
SELECT * FROM Medicos--2
SELECT * FROM Pacientes--2
SELECT * FROM Recetas--2
SELECT * FROM Servicios--2
GO
--2. Crea Crear los siguientes schemas: Pacientes, Personal, Consultas, Hospitalizacion, Farmacia, Facturacion y Administracion
CREATE SCHEMA PACIENTES;
GO
CREATE SCHEMA PERSONAL;
GO
CREATE SCHEMA CONSULTAS;
GO
CREATE SCHEMA HOSPITALIZACION;
GO
CREATE SCHEMA FARMACIA
GO
CREATE SCHEMA FACTURACION 
GO
CREATE SCHEMA ADMINISTRACION;
GO
SELECT * FROM SYS.schemas
WHERE principal_id=1
--3. Mover las tablas a su schema.
--Pacientes : Pacientes
ALTER SCHEMA PACIENTES TRANSFER DBO.Pacientes
--Personal: Medicos, Enfermeros,Especialidades
ALTER SCHEMA Personal TRANSFER DBO.MEDICOS
ALTER SCHEMA Personal TRANSFER DBO.Enfermeros
ALTER SCHEMA Personal TRANSFER DBO.Especialidades
--Administracion:Consultorios, Departamentos
ALTER SCHEMA Administracion TRANSFER DBO.Consultorios
ALTER SCHEMA Administracion TRANSFER DBO.Departamentos
--Consultas: Citas,ConsultasMedicas
ALTER SCHEMA Consultas TRANSFER DBO.Citas
ALTER SCHEMA Consultas TRANSFER DBO.ConsultasMedicas
--Hospitalizacion:Internamientos,Habitaciones
ALTER SCHEMA Hospitalizacion TRANSFER DBO.Internamientos
ALTER SCHEMA Hospitalizacion TRANSFER DBO.Habitaciones
--Farmacia: Medicamentos,Recetas,DetalleReceta
ALTER SCHEMA Farmacia TRANSFER DBO.Medicamentos
ALTER SCHEMA Farmacia TRANSFER DBO.Recetas
ALTER SCHEMA Farmacia TRANSFER DBO.DetalleReceta
--Facturacion: Servicios,Factura,DetalleFactura
ALTER SCHEMA Facturacion TRANSFER DBO.Servicios
ALTER SCHEMA Facturacion TRANSFER DBO.Facturas
ALTER SCHEMA Facturacion TRANSFER DBO.DetalleFactura
--
SELECT O.name AS 'TABLA', S.name AS 'ESQUEMA', U.name AS 'PROPIETARIO'
FROM SYS.objects O
INNER JOIN SYS.schemas S ON (O.schema_id=S.schema_id)
INNER JOIN SYS.sysusers U ON (U.uid=S.principal_id)
WHERE TYPE='U'
ORDER BY S.name
--4. Crear un rol para cada schema y otorga permisos diferentes tu elije cuales. Juega con permisos con GRANT y permisos con roles fijos de bases de datos.
CREATE ROLE RPACIENTES;
CREATE ROLE RPERSONAL;
CREATE ROLE RCONSULTAS;
CREATE ROLE RHOSPITALIZACION;
CREATE ROLE RFARMACIA
CREATE ROLE RFACTURACION 
CREATE ROLE RADMINISTRACION;
--
GRANT SELECT ON OBJECT::CONSULTAS.CITAS TO RPACIENTES  
GRANT SELECT ON OBJECT::PACIENTES.PACIENTES TO RPACIENTES  
--
GRANT SELECT,UPDATE,DELETE,INSERT ON SCHEMA::PERSONAL TO RPERSONAL  
--
EXEC sp_addrolemember DB_DATAREADER,RCONSULTAS
--
GRANT SELECT,INSERT,DELETE,UPDATE ON SCHEMA::HOSPITALIZACION TO RHOSPITALIZACION
--
GRANT SELECT,INSERT,DELETE,UPDATE ON SCHEMA::FARMACIA TO RFARMACIA
--
GRANT SELECT ON OBJECT:: PACIENTES.PACIENTES TO RFARMACIA 
--
GRANT SELECT,INSERT,DELETE,UPDATE ON SCHEMA::FACTURACION TO RFACTURACION
--
GRANT SELECT ON SCHEMA::HOSPITALIZACION TO RFACTURACION
--
GRANT SELECT ON SCHEMA::PACIENTES TO RFACTURACION
--
ALTER ROLE DB_DATAWRITER ADD MEMBER RADMINISTRACION
--
ALTER ROLE DB_DATAREADER ADD MEMBER RADMINISTRACION
--5. Crea un rol adicional superAdmin que pueda tener permisos de todos los comandos ddl, escritura, lectura
CREATE ROLE SUPERADMIN;
--
EXEC sp_addrolemember DB_DATAWRITER,SUPERADMIN
EXEC sp_addrolemember DB_DATAreader,SUPERADMIN
EXEC sp_addrolemember DB_DDLADMIN,SUPERADMIN
--6. Crea 2 usuarios y 2 logins para cada rol, agregalos
--CREATE ROLE RPACIENTES;
CREATE LOGIN PACIENTE1 WITH PASSWORD='1234'
CREATE LOGIN PACIENTE2 WITH PASSWORD='1234'
--
CREATE USER UPACIENTE1 FOR LOGIN PACIENTE1 WITH DEFAULT_SCHEMA=PACIENTE;
CREATE USER UPACIENTE2 FOR LOGIN PACIENTE2 WITH DEFAULT_SCHEMA=PACIENTE;
--
EXEC sp_addrolemember RPACIENTES,UPACIENTE1
EXEC sp_addrolemember RPACIENTES,UPACIENTE2
--CREATE ROLE RPERSONAL;
CREATE LOGIN PERSONAL1 WITH PASSWORD='1234'
CREATE LOGIN PERSONAL2 WITH PASSWORD='1234'
--
CREATE USER UPERSONAL1 FOR LOGIN PERSONAL1;
CREATE USER UPERSONAL2 FOR LOGIN PERSONAL2;
--
EXEC sp_addrolemember RPERSONAL,UPERSONAL1
EXEC sp_addrolemember RPERSONAL,UPERSONAL2
--CREATE ROLE RCONSULTAS;
CREATE LOGIN CONSULTAS1 WITH PASSWORD='1234'
CREATE LOGIN CONSULTAS2 WITH PASSWORD='1234'
--
CREATE USER UCONSULTAS1 FOR LOGIN CONSULTAS1;
CREATE USER UCONSULTAS2 FOR LOGIN CONSULTAS2;
--
EXEC sp_addrolemember RCONSULTAS,UCONSULTAS1
EXEC sp_addrolemember RCONSULTAS,UCONSULTAS2
--CREATE ROLE RHOSPITALIZACION;
CREATE LOGIN HOSPITALIZACION1 WITH PASSWORD='1234'
CREATE LOGIN HOSPITALIZACION2 WITH PASSWORD='1234'
--
CREATE USER UHOSPITALIZACION1 FOR LOGIN HOSPITALIZACION1;
CREATE USER UHOSPITALIZACION2 FOR LOGIN HOSPITALIZACION2;
--
EXEC sp_addrolemember RHOSPITALIZACION,UHOSPITALIZACION1
EXEC sp_addrolemember RHOSPITALIZACION,UHOSPITALIZACION2
--CREATE ROLE RFARMACIA
CREATE LOGIN FARMACIA1 WITH PASSWORD='1234'
CREATE LOGIN FARMACIA2 WITH PASSWORD='1234'
--
CREATE USER UFARMACIA1 FOR LOGIN FARMACIA1;
CREATE USER UFARMACIA2 FOR LOGIN FARMACIA2;
--
EXEC sp_addrolemember RFARMACIA,UFARMACIA1
EXEC sp_addrolemember RFARMACIA,UFARMACIA2
--CREATE ROLE RFACTURACION 
CREATE LOGIN FACTURACION1 WITH PASSWORD='1234'
CREATE LOGIN FACTURACION2 WITH PASSWORD='1234'
--
CREATE USER UFACTURACION1 FOR LOGIN FACTURACION1;
CREATE USER UFACTURACION2 FOR LOGIN FACTURACION2;
--
EXEC sp_addrolemember RFACTURACION,UFACTURACION1
EXEC sp_addrolemember RFACTURACION,UFACTURACION2
--CREATE ROLE RADMINISTRACION;
CREATE LOGIN ADMINISTRACION1 WITH PASSWORD='1234'
CREATE LOGIN ADMINISTRACION2 WITH PASSWORD='1234'
--
CREATE USER UADMINISTRACION1 FOR LOGIN ADMINISTRACION1;
CREATE USER UADMINISTRACION2 FOR LOGIN ADMINISTRACION2;
--
EXEC sp_addrolemember RADMINISTRACION,UADMINISTRACION1
EXEC sp_addrolemember RADMINISTRACION,UADMINISTRACION2
--CREATE ROLE SUPERADMIN;
CREATE LOGIN SUPERADMIN1 WITH PASSWORD='1234'
CREATE LOGIN SUPERADMIN2 WITH PASSWORD='1234'
--
CREATE USER USUPERADMIN1 FOR LOGIN SUPERADMIN1;
CREATE USER USUPERADMIN2 FOR LOGIN SUPERADMIN2;
--
EXEC sp_addrolemember SUPERADMIN,USUPERADMIN1
EXEC sp_addrolemember SUPERADMIN,USUPERADMIN2
--7. Prueba los permisos de cada tipo de usuario haz acciones de las que le diste permisos y de las que no.
--PRUBEA SUPERADMIN
CREATE TABLE TABLASUPER(
	ID INT,
	DESCRIPCION VARCHAR(20)
)
DROP TABLE TABLASUPER
--NO FUNCIONA
CREATE LOGIN SUPA2 WITH PASSWORD='1234'
--PRUEBA HOSPITALIZACION
SELECT * FROM HOSPITALIZACION.Habitaciones
INSERT INTO HOSPITALIZACION.Habitaciones
VALUES(10,5,1,1)
UPDATE HOSPITALIZACION.Habitaciones
SET NumeroHabitacion=15
--NO FUNCIONA
CREATE TABLE HOSPI
(ID INT,
NOMBRE VARCHAR(50))
--PRUEBA PACIENTE
--FUNCIONA
SELECT * FROM CONSULTAS.Citas
SELECT * FROM PACIENTES.Pacientes
--NO FUNCIONA
SELECT * FROM [ADMINISTRACION].[Consultorios]
--8.1 MUESTRA LOS SCHEMAS Y SUS TABLAS Y PROPIETARIOS
SELECT O.name AS 'TABLA', S.name AS 'ESQUEMA', U.name AS 'PROPIETARIO'
FROM SYS.objects O
INNER JOIN SYS.schemas S ON (O.schema_id=S.schema_id)
INNER JOIN SYS.sysusers U ON (U.uid=S.principal_id)
WHERE TYPE='U'
ORDER BY S.name
--8.2 MUENSTRA LOS USUARIOS
SELECT * FROM SYS.database_principals
WHERE TYPE='S'
--8.3 MUESTRA LOS ROLES Y SUS MIEMBROS
SELECT * FROM SYS.database_principals
WHERE TYPE='R'
EXEC sp_helprolemember
EXEC sp_helprole
