USE Northwind
GO
-- 11. CONECTARSE Y PROBAR UN USUARIO VENDEDOR
-- 11.1 HACER INSERT
INSERT INTO CATALOGOS.Categories
(CategoryName,[Description])
VALUES ('NUEVA CATEGORIA','MI CATEGORIA')
GO
SELECT * FROM CATALOGOS.Categories
-- 11.2 HACER CREATE TABLE
CREATE TABLE PRUEBAPERMISOS
(
 LLAVE INT IDENTITY(1,1) PRIMARY KEY,
 DESCRIPCION VARCHAR(100)
)
--
CREATE TABLE VENTAS.PRUEBA2
(
 LLAVE INT IDENTITY(1,1) PRIMARY KEY,
 DESCRIPCION VARCHAR(100)
)
GO
-- 11.3 CREATE LOGIN
CREATE LOGIN CHRIS WITH PASSWORD='1234';
-- 11.4 CREATE USER
CREATE USER CHRIS FOR LOGIN CHRIS;
GO
--11.5 CREAMOS ESQUEMA
CREATE SCHEMA SCHEMPRUEBA_VENDEDOR;
GO
--13. Volver a conectarte con el usuario Vendedor y cambia las tablas a la que al
--esquema que creaste.
ALTER SCHEMA SCHEMPRUEBA_VENDEDOR TRANSFER [CATALOGOS].[CustomerCustomerDemo]