--PRACTICA 1
--UNIDAD 3
--NUÑEZ CARVAJAL JOSE TADEO
--02-03-2026

USE Northwind
GO
--1 ACTUALIZAR LAS FECHAS
UPDATE VENTAS.Orders SET OrderDate=DATEADD(YEAR,28,OrderDate),
[RequiredDate]=DATEADD(YEAR,28,[RequiredDate]),
[ShippedDate]=DATEADD(YEAR,28,[ShippedDate]);
UPDATE CATALOGOS.Employees SET BirthDate=DATEADD(YEAR,28,BirthDate),
HireDate=DATEADD(YEAR,28,HireDate)
--2 VERIFICAMOS LOS ESQUEMAS DE LA BD
SELECT * FROM SYS.schemas
GO
--3 CREAR DOS ESQUEMAS(DBO--LOGIN sa) 
CREATE SCHEMA VENTAS
GO
--
CREATE SCHEMA CATALOGOS
AUTHORIZATION DBO
GO
--
CREATE LOGIN lPRACTICA1
WITH PASSWORD ='1234'
--
CREATE USER lPRACTICA1
FOR LOGIN lPRACTICA1
GO
--
CREATE SCHEMA PRACTICA1
AUTHORIZATION lPRACTICA1
GO
--4 VERIFICAR DE NUEVO LOS ESQUEMAS
SELECT * FROM SYS.schemas
--5 CAMBIAR LAS TABLAS A DONDE DEBEN DE ESTAR
ALTER SCHEMA  VENTAS TRANSFER DBO.ORDERS;
ALTER SCHEMA  VENTASTRANSFER DBO.PRODUCTS;
ALTER SCHEMA  VENTAS TRANSFER [DBO].[ORDER DETAILS];
--
ALTER SCHEMA CATALOGOS TRANSFER DBO.CATEGORIES
ALTER SCHEMA CATALOGOS TRANSFER DBO.CustomerCustomerDemo
ALTER SCHEMA CATALOGOS TRANSFER DBO.CustomerDemographics
ALTER SCHEMA CATALOGOS TRANSFER DBO.[Customers]
ALTER SCHEMA CATALOGOS TRANSFER DBO.[Employees]
ALTER SCHEMA CATALOGOS TRANSFER DBO.[EmployeeTerritories]
ALTER SCHEMA CATALOGOS TRANSFER DBO.[Region]
ALTER SCHEMA CATALOGOS TRANSFER DBO.[Shippers]
ALTER SCHEMA CATALOGOS TRANSFER DBO.[Suppliers]
ALTER SCHEMA CATALOGOS TRANSFER DBO.[Territories]
--6 VERIFICAR QUE LAS TABLAS
SELECT
O.name AS 'TABLA',
S.name AS 'ESQUEMA',
U.name AS 'PROPIETARIO'
FROM SYS.objects O
INNER JOIN SYS.schemas S ON (O.schema_id=S.schema_id)
INNER JOIN SYS.sysusers U ON (U.uid=s.principal_id)
WHERE O.type='U'
ORDER BY S.name
--6 CREA DOS ROLES: CAPTURISTAS Y VENDEDOR
CREATE ROLE CAPTURISTA
CREATE ROLE VENDEDOR
--7 PERMISOS A TRAVES DE ROLES PREDEFINIDOS
--7.1 ROL CAPTURISTA-- LECTURA Y ESCRITURA
EXEC sp_addrolemember db_datawriter,CAPTURISTA;
EXEC sp_addrolemember db_datareader,CAPTURISTA;
--7.2 ROL VENDEDOR: CREAR TABLAS, VISTAS, CREAR USUARIOS
EXEC sp_addrolemember db_datawriter,VENDEDOR;
EXEC sp_addrolemember db_datareader,VENDEDOR;
EXEC sp_addrolemember db_ddladmin,VENDEDOR;
EXEC sp_addrolemember db_securityadmin,VENDEDOR;
EXEC sp_addrolemember  DB_ACCESSADMIN,VENDEDOR;
--8 CREAR 3 USUARIOS Y LOGINS Y AGREGARLOS PARA QUE SEAN CAPTURISTAS
CREATE LOGIN MARIA WITH PASSWORD='1234'
CREATE LOGIN NOE WITH PASSWORD='1234'
CREATE LOGIN LUPITA WITH PASSWORD='1234'
--
CREATE USER MARIA FOR LOGIN MARIA
CREATE USER NOE FOR LOGIN NOE
CREATE USER LUPITA FOR LOGIN LUPITA
--
exec sp_addrolemember CAPTURISTA,MARIA
exec sp_addrolemember CAPTURISTA, NOE
exec sp_addrolemember CAPTURISTA, LUPITA
--9 CREAR 2 USUARIOS Y LOGINS Y AGREGARLOS PARA QUE SEAN VENDEDOR
CREATE LOGIN ISELA WITH PASSWORD='1234'
CREATE LOGIN MAGA WITH PASSWORD='1234'
--
CREATE USER ISELA FOR LOGIN ISELA
CREATE USER MAGA FOR LOGIN MAGA
--
exec sp_addrolemember VENDEDOR,ISELA
exec sp_addrolemember VENDEDOR,MAGA
--
EXEC sp_addsrvrolemember ISELA,securityadmin
EXEC sp_addsrvrolemember MAGA,securityadmin
--12. Regresar a sa y cambiar el propietario a la tabla CustomerCustomerDemo y
--CustomerDemographics que sea VENDEDOR. Para que te conectes con el
--usuario del rol vendedor pueda hacer transfer schema.
ALTER AUTHORIZATION ON OBJECT::[CATALOGOS].[CustomerCustomerDemo] TO ISELA
ALTER AUTHORIZATION ON OBJECT::[CATALOGOS].[CustomerDemographics] TO MAGA
--14. Regresa a sa y Consulta a que esquema pertenece cada tabla.
SELECT O.name,S.name,U.name
FROM SYS.objects O
INNER JOIN SYS.SCHEMAS S ON (O.schema_id=S.schema_id)
INNER JOIN SYS.sysusers U ON (S.principal_id=U.uid)
--15. Consultar los roles de la bd, los miembros de cada role y los privilegios de cada role.
EXEC sp_helprole
EXEC sp_helprolemember CAPTURISTA
EXEC sp_helprolemember VENDEDOR


